@startuml yonde
' hide the spot
hide circle

' avoid problems with angled crows feet
skinparam linetype ortho

entity "site_contents" as site_contents {
  id
  --
  site_content_id
  site_content_sub_id
  category
  related_number
  related_number2
  title
  body
  body1
  body2
  pref_cd<<FK>>
  content1_path
  content2_path
  posting_start_date
  posting_end_date
  is_floating
  is_posting
  is_posting_sg
  is_posting_ex
  is_posting_noen
  is_posting_sgex
  is_posting_gj
  is_posting_madoguchi
  is_posting_gm
  is_posting_ueki
  is_posting_tatsujin_mypage
  is_posting_tatsujin_bp
  is_posting_all
  created_at
  updated_at
}


entity "divisions" as divisions {
  id
  --
  division_id
  division_name
  division_name_short
  created_at
  updated_at
}

entity "gm_sites" as gm_sites {
  id
  --
  gm_site_id
  site_name
  site_url
  created_at
  updated_at
}

entity "prefs" as prefs {
  pref_id
  --
  pref_name
  area_id
}


entity "areas" as areas {
  id
  --
  area_id
  gm_site_id<<FK>>
  regional_area_kubun
  area_pref_cd<<FK>>
  area_name
  content_path
  body
  created_at
  updated_at
}

entity "cities" as cities {
  id
  --
  pref_cd<<FK>>
  city_cd
  city_name
  created_at
  updated_at
}

entity "area_configuration_cities" as area_configuration_cities {
  id
  --
  area_configuration_city_id
  area_id<<FK>>
  area_code<<FK>>
  created_at
  updated_at
}

entity "tags" as tags {
  id
  --
  division_id<<FK>>
  tag_code
  major_category
  middle_category
  minor_category
  tag_name
  created_at
  updated_at
}

entity "contents_tags" as contents_tags {
  id
  --
  site_content_id<<FK>>
  tag_code<<FK>>
  created_at
  updated_at
}

divisions ||--o{ tags
tags ||--o{ contents_tags
site_contents ||--o{ contents_tags
gm_sites ||--o{ areas
areas ||--o{ area_configuration_cities
cities ||--o{ area_configuration_cities
prefs ||--o{ areas
prefs ||--o{ cities

@enduml